# Generated by Django 3.2.12 on 2023-12-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_maintenance', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
